version: '3.8'
 
services:
  web:
    build: .
    image: front-venta-repuestos
    container_name: front-venta-repuestos
    ports:
      - "80:80"
    restart: unless-stopped
 
  jenkins:
    image: jenkins/jenkins:lts        # <-- aquí ya no hay build, sólo image
    container_name: ci_jenkins
    user: root                        # corre como root para poder usar docker.sock
    privileged: true
    ports:
      - "8081:8081"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
 
volumes:
  jenkins_home: