version: '3.8'
services:
  web:
    build: .
    image: front-venta-repuestos
    container_name: front-venta-repuestos
    ports: ["80:80"]
    restart: unless-stopped
 
  jenkins:
    build:
      context: ./jenkins
    image: ci_jenkins
    container_name: ci_jenkins
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
 
volumes:
  jenkins_home: