version: '3.8'
 
services:
  web:
    build: .
    image: front-venta-repuestos
    container_name: front-venta-repuestos
    ports:
      - "8080:80"    
    restart: unless-stopped
 
  jenkins:
    build:
      context: ./jenkins        # <— aquí está tu Dockerfile de Jenkins
    image: ci_jenkins
    container_name: ci_jenkins
    user: root                  # para evitar permisos con el socket
    privileged: true
    ports:
      - "8081:8080" 
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
 
volumes:
  jenkins_home: